# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/kinetic64"

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 8082, host: 8082
  config.vm.network "forwarded_port", guest: 8083, host: 8083
  config.vm.network "forwarded_port", guest: 8084, host: 8084
  config.vm.network "forwarded_port", guest: 8085, host: 8085
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.synced_folder ".", "/vagrant", disabled: true         # Disable default shared folder
  config.vm.synced_folder "..", "/data"                           # Share project with VM
  config.vm.synced_folder "../..", "/projects"                    # Share project with VM
  config.vm.synced_folder "../..", "/projects"                    # Share project with VM
  config.vm.synced_folder "../../../MosaicMill Dropbox/", "/dropbox"

  config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    #
    # Customize the amount of memory on the VM:
    vb.memory = "8192"
    vb.cpus = 3
    # vb.customize ["modifyvm", :id, "--vram", "64"]

    # Set the name of the VM to include path to Vagrant file so that it is possible to
    # have multiple machinies running from diferent repos
    vb.name = "dev-machine-ubuntu"
  end

  config.vm.provision "shell", inline: <<-SHELL
     apt update
     apt-get install -y ansible
     ansible-playbook -vv /data/ubuntu/vm.yml
  SHELL

end
