---
- hosts: localhost
  tasks:
    - become: yes
      apt:
        name:
          - "curl"
          - "ca-certificates"
          - "curl"
          - "gnupg"
          - "lsb-release"
          - "dpkg"
          - "tig"

    - become: yes
      shell: |
        /usr/bin/bash
        set -euo pipefail

        docker_installed=1
        which docker || docker_installed=0
        if [ $docker_installed -eq 1 ]; then
            echo "Docker already configued"
            exit 0
        fi
        if [ ! -f /usr/share/keyrings/docker-archive-keyring.gpg ]; then
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        fi
        if [ ! -f /etc/apt/sources.list.d/docker.list ]; then
            echo \
           "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
           $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        fi
        apt-get update
      args:
        executable: /usr/bin/bash

    - become: yes
      apt:
        name:
          - "docker-ce"
          - "docker-ce-cli"
          - "containerd.io"

    - user:
        name: vagrant
        groups: docker
        append: yes
