# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "debian/bullseye64"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Share project with VM
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../..", "/projects"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    #
    # Customize the amount of memory on the VM:
    vb.memory = "8192"
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--vram", "128"]

    # Set the name of the VM to include path to Vagrant file so that it is possible to
    # have multiple machinies running from diferent repos
    vb.name = "dev-machine-debian"
  end

  # Install puppet on VM
  config.vm.provision "shell", inline: <<-SHELL
     ansible_installed=1
     command -v ansible || ansible_installed=0
     if [ $ansible_installed -eq 0 ]; then
         apt update
         apt install -y gnupg
         echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu focal main" > /etc/apt/sources.list.d/ubuntu-ansible.list
         sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
         apt update
         apt install -y ansible
     else
         echo "Ansible already installed"
     fi
     ansible-playbook -vv /projects/virtual-environments/debian/vm.yml
  SHELL

end
