# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  username = "vagrant"
  user_id = 1234
  user_group_id = 1234

  config.vm.box = "debian/contrib-jessie64"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Share project with VM
  config.vm.synced_folder ".", "/home/#{username}/mount"
  config.vm.synced_folder "../data", "/home/#{username}/data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    #
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--vram", "64"]

    # Set the name of the VM to include path to Vagrant file so that it is possible to
    # have multiple machinies running from diferent repos
    vb.name = "dev-machine"
  end

  # Install puppet on VM
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y puppet
  SHELL

  config.vm.provision "puppet" do |puppet|
    puppet.facter = {
      "user" => "#{username}",
      "user_id" => "#{user_id}",
      "user_group_id" => "#{user_group_id}",
    }

    puppet.manifests_path = "manifests"
    puppet.manifest_file = "default.pp"

    # Uncomment to debug
    # puppet.options = "--verbose --debug"
  end
end
